blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://community.aura.io
    about: Suggest an idea for this project
  - name: Question / Problem
    url: https://community.aura.io
    about: Questions and problems with aura
  - name: aura Security Vulnerability
    url: https://aura.io/legal/#vulnerability
    about: Learn about our Vulnerability Disclosure Policy
