name: Playwright Tests - Nightly

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      image:
        description: 'Docker image to test against'
        required: false
        default: 'auraio/aura:nightly'
        type: string
  push:
    branches:
      - ci-containers-nightly

jobs:
  test-configurations:
    strategy:
      fail-fast: false
      matrix:
        config: [standard, postgres]
    name: Test ${{ matrix.config }}
    uses: ./.github/workflows/playwright-test-reusable.yml
    with:
      test-mode: docker-pull
      docker-image: ${{ github.event.inputs.image || 'auraio/aura:nightly' }}
      test-command: pnpm --filter=aura-playwright test:container:${{ matrix.config }}
    secrets: inherit
