name: Run Playwright Tests (Docker Pull)
# This workflow is used to run Playwright tests in a Docker container pulled from the registry

on:
  workflow_call:
    inputs:
      shards:
        description: 'Shards for parallel execution'
        required: false
        default: '[1]'
        type: string
      image:
        description: 'Image to use'
        required: false
        default: 'auraio/aura:nightly'
        type: string
  workflow_dispatch:
    inputs:
      shards:
        description: 'Shards for parallel execution'
        required: false
        default: '[1]'
        type: string
      image:
        description: 'Image to use'
        required: false
        default: 'auraio/aura:nightly'
        type: string

jobs:
  build-and-test:
    uses: ./.github/workflows/playwright-test-reusable.yml
    with:
      test-mode: docker-pull
      shards: ${{ inputs.shards }}
      docker-image: ${{ inputs.image }}
      test-command: pnpm --filter=aura-playwright test:container:standard
    secrets: inherit
